language: python

branches:
  only:
    - master
    - /^\d+\.\d+\.X$/

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "2.7"
      dist: trusty
      env: TOXENV=py27
    - python: "3.4"
      dist: trusty
      env: TOXENV=py34
    - python: "3.5"
      dist: trusty
      env: TOXENV=py35
    - python: "3.6"
      dist: trusty
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: "pypy"
      dist: trusty
      env: TOXENV=pypy
    - python: "pypy3.5-5.10.1"
      dist: trusty
      env: TOXENV=pypy3
    - python: "3.7"
      dist: xenial
      env: TOXENV=lint

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
script:
  - tox
